version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r mlops_l1/requirements.txt

  build:
    commands:
      - python mlops_l1/mlops_l1.py

  post_build:
    commands:
      - aws s3 cp mlops_l1/telecom_tower_failure_model.pkl s3://telecom-mlops-model-storage5/

artifacts:
  files:
    - mlops_l1/telecom_tower_failure_model.pkl